//
//  Configuration.h
//  GeniusReferrals
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
//
#ifndef GeniusReferrals_Configuration_h
#define GeniusReferrals_Configuration_h

/** The base Uri for API calls */
extern NSString* Configuration_BaseUri;

/** The content type */
/** extern reference to the config variable ContentType */
extern NSString* Configuration_ContentType;

/** Your API Token, you can get your token here https://www.geniusreferrals.com/en/settings/api-access */
/** extern reference to the config variable XAuthToken */
extern NSString* Configuration_XAuthToken;

#endif
