//
//  Configuration.m
//  GeniusReferrals
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/17/2017
//
#import "Configuration.h"

/** The base Uri for API calls */
NSString* Configuration_BaseUri = @"https://api.geniusreferrals.com";

/** The content type */
/** Replace the value of ContentType with an appropriate value */
NSString* Configuration_ContentType = @"application/json";

/** Your API Token, you can get your token here https://www.geniusreferrals.com/en/settings/api-access */
/** Replace the value of XAuthToken with an appropriate value */
NSString* Configuration_XAuthToken = @"3b9d11374b602fb47b987dff90f1c5940a1f377f";

