//
//  AdvocatePatchForm.h
//  GeniusReferrals
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
//
#ifndef APIMATIC_ADVOCATEPATCHFORM
#define APIMATIC_ADVOCATEPATCHFORM

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol AdvocatePatchForm
@end

@interface AdvocatePatchForm : JSONModel

/**
* The advocate's name
*/
@property NSString* name;

/**
* The advocate's last name
*/
@property NSString* lastname;

/**
* The advocate's email
*/
@property NSString* email;

/**
* TODO: Write general description for this field
*/
@property NSNumber* payoutThreshold;

/**
* The total amount of bonuses that the advocate must generate before being able to create a bonus redemption request.
*/
@property NSNumber* claimedBalance;

/**
* The unclaimed balance
*/
@property NSNumber* unclaimedBalance;

/**
* The currency code
*/
@property NSString* currencyCode;

/**
* The advocate's avatar URL
*/
@property NSString* avatarUrl;

/**
* Useful to store extra information about the advocate. e.g, the phone number, address, etc.
*/
@property NSString* metadata;

/**
* Whether or not the advocate is allowed to refer services/products (Useful when using the Full Widget template).
*/
@property NSNumber* canRefer;

/**
* The advocate's token
*/
@property NSString* token;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif