//
//  AdvocateForm.h
//  GeniusReferrals
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/17/2017
//
#ifndef APIMATIC_ADVOCATEFORM
#define APIMATIC_ADVOCATEFORM

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "Advocate.h"


//protocol defined for deserialization of JSON
@protocol AdvocateForm
@end

@interface AdvocateForm : JSONModel

/**
* The advocate's wrapper
*/
@property Advocate* advocate;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif