//
//  Bonuses1.m
//  GeniusReferrals
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/17/2017
//
#import "Bonuses1.h"

@implementation Bonuses1

/**
* The referral's token.
*/
@synthesize advocateToken;

/**
* The reference number for this request. Usually the order_id, payment_id, or timestamp.
*/
@synthesize reference;

/**
* The bonus amount to give to the advocate.
*/
@synthesize bonusAmount;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"advocate_token": @"advocateToken",
        @"reference": @"reference",
        @"bonus_amount": @"bonusAmount"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end