//
//  ForceBonusesForm.h
//  GeniusReferrals
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
//
#ifndef APIMATIC_FORCEBONUSESFORM
#define APIMATIC_FORCEBONUSESFORM

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "ForceBonuses.h"


//protocol defined for deserialization of JSON
@protocol ForceBonusesForm
@end

@interface ForceBonusesForm : JSONModel

/**
* The bonuses' wrapper
*/
@property ForceBonuses* bonus;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif