//
//  PaymentMethod.h
//  GeniusReferrals
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
//
#ifndef APIMATIC_PAYMENTMETHOD
#define APIMATIC_PAYMENTMETHOD

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol PaymentMethod
@end

@interface PaymentMethod : JSONModel

/**
* The username
*/
@property NSString* username;

/**
* The description
*/
@property NSString* description;

/**
* Is the payment method active? (true, false)
*/
@property NSData* isActive;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif