//
//  PaymentMethodForm.h
//  GeniusReferrals
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
//
#ifndef APIMATIC_PAYMENTMETHODFORM
#define APIMATIC_PAYMENTMETHODFORM

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "PaymentMethod.h"


//protocol defined for deserialization of JSON
@protocol PaymentMethodForm
@end

@interface PaymentMethodForm : JSONModel

/**
* The payment methods wrapper
*/
@property PaymentMethod* advocatePaymentMethod;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif