//
//  RedemptionRequest.h
//  GeniusReferrals
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/17/2017
//
#ifndef APIMATIC_REDEMPTIONREQUEST
#define APIMATIC_REDEMPTIONREQUEST

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol RedemptionRequest
@end

@interface RedemptionRequest : JSONModel

/**
* The advocate's token
*/
@property NSString* advocateToken;

/**
* The request status identifier
*/
@property NSString* requestStatusSlug;

/**
* The request action identifier
*/
@property NSString* requestActionSlug;

/**
* The currency code
*/
@property NSString* currencyCode;

/**
* The amount to be redeemed
*/
@property int amount;

/**
* The description of the requests, useful to store extra information about the request.
*/
@property NSString* description;

/**
* The advocate's PayPal username
*/
@property NSString* advocatesPaypalUsername;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif