//
//  RedemptionRequest.m
//  GeniusReferrals
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
//
#import "RedemptionRequest.h"

@implementation RedemptionRequest

/**
* The advocate's token
*/
@synthesize advocateToken;

/**
* The request status identifier
*/
@synthesize requestStatusSlug;

/**
* The request action identifier
*/
@synthesize requestActionSlug;

/**
* The currency code
*/
@synthesize currencyCode;

/**
* The amount to be redeemed
*/
@synthesize amount;

/**
* The description of the requests, useful to store extra information about the request.
*/
@synthesize description;

/**
* The advocate's PayPal username
*/
@synthesize advocatesPaypalUsername;



/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"advocate_token": @"advocateToken",
        @"request_status_slug": @"requestStatusSlug",
        @"request_action_slug": @"requestActionSlug",
        @"currency_code": @"currencyCode",
        @"amount": @"amount",
        @"description": @"description",
        @"advocates_paypal_username": @"advocatesPaypalUsername"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end