//
//  RedemptionRequestForm.h
//  GeniusReferrals
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/17/2017
//
#ifndef APIMATIC_REDEMPTIONREQUESTFORM
#define APIMATIC_REDEMPTIONREQUESTFORM

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "RedemptionRequest.h"


//protocol defined for deserialization of JSON
@protocol RedemptionRequestForm
@end

@interface RedemptionRequestForm : JSONModel

/**
* The redemption request's wrapper
*/
@property RedemptionRequest* redemptionRequest;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif