//
//  Referral.h
//  GeniusReferrals
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
//
#ifndef APIMATIC_REFERRAL
#define APIMATIC_REFERRAL

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol Referral
@end

@interface Referral : JSONModel

/**
* The referrals token
*/
@property NSString* referredAdvocateToken;

/**
* The referral origin identifier
*/
@property NSString* referralOriginSlug;

/**
* The campaign identifier
*/
@property NSString* campaignSlug;

/**
* The http_referrer URL
*/
@property NSString* httpReferer;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end
#endif