//
//  AdvocatesController.h
//  GeniusReferrals
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/17/2017
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"
#import "AdvocateForm.h"
#import "AdvocatePatchForm.h"

@interface AdvocatesController : BaseController

/**
* Completion block definition for asynchronous call to Delete Advocate */
typedef void (^CompletedDeleteAdvocate)(BOOL success, HttpContext* context, NSError* error);

/**
* Delete an advocate
* @param    accountSlug    Required parameter: The account identifier
* @param    advocateToken    Required parameter: The advocate's token
*/
- (void) deleteAdvocateAsyncWithAccountSlug:(NSString*) accountSlug
                advocateToken:(NSString*) advocateToken
                completionBlock:(CompletedDeleteAdvocate) onCompleted;

/**
* Completion block definition for asynchronous call to Put Advocate */
typedef void (^CompletedPutAdvocate)(BOOL success, HttpContext* context, NSError* error);

/**
* Update an advocate.
* @param    accountSlug    Required parameter: The account identifier
* @param    advocateToken    Required parameter: The advocate's token
* @param    advocateForm    Required parameter: The body of the request
*/
- (void) putAdvocateAsyncWithAccountSlug:(NSString*) accountSlug
                advocateToken:(NSString*) advocateToken
                advocateForm:(AdvocateForm*) advocateForm
                completionBlock:(CompletedPutAdvocate) onCompleted;

/**
* Completion block definition for asynchronous call to Post Advocate */
typedef void (^CompletedPostAdvocate)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* Create a new advocate.
* @param    accountSlug    Required parameter: The account identifier
* @param    advocateForm    Required parameter: The body of the request
*/
- (void) postAdvocateAsyncWithAccountSlug:(NSString*) accountSlug
                advocateForm:(AdvocateForm*) advocateForm
                completionBlock:(CompletedPostAdvocate) onCompleted;

/**
* Completion block definition for asynchronous call to Get Advocate */
typedef void (^CompletedGetAdvocate)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* Get an advocate by a given token.
* @param    accountSlug    Required parameter: The account identifier
* @param    advocateToken    Required parameter: The advocate's token
*/
- (void) getAdvocateAsyncWithAccountSlug:(NSString*) accountSlug
                advocateToken:(NSString*) advocateToken
                completionBlock:(CompletedGetAdvocate) onCompleted;

/**
* Completion block definition for asynchronous call to Delete Advocates */
typedef void (^CompletedDeleteAdvocates)(BOOL success, HttpContext* context, NSError* error);

/**
* Delete all advocates
* @param    accountSlug    Required parameter: The account identifier
*/
- (void) deleteAdvocatesAsyncWithAccountSlug:(NSString*) accountSlug
                completionBlock:(CompletedDeleteAdvocates) onCompleted;

/**
* Completion block definition for asynchronous call to Get Advocates */
typedef void (^CompletedGetAdvocates)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* Get the list of advocates
* @param    accountSlug    Required parameter: The account identifier
* @param    page    Optional parameter: Page number, e.g. 1 would start at the first result, and 10 would start at the tenth result.
* @param    limit    Optional parameter: Maximum number of results to return in the response. Default (10), threshold (100)
* @param    filter    Optional parameter: Allowed fields: name, lastname, email, advocate_token, bonus_exchange_method_slug, campaign_slug, can_refer, is_referral, from, to, created. Use the following delimiters to build your filters params. The vertical bar ('\|') to separate individual filter phrases and a double colon ('::') to separate the names and values. The delimiter of the double colon (':') separates the property name from the comparison value, enabling the comparison value to contain spaces. Example: www.example.com/users?filter='name::todd\|city::denver\|title::grand poobah'
* @param    sort    Optional parameter: Allowed fields: name, lastname, email, created. Use sort query-string parameter that contains a delimited set of property names. For each property name, sort in ascending order, and for each property prefixed with a dash ('-') sort in descending order. Separate each property name with a vertical bar ('\|'), which is consistent with the separation of the name\|value pairs in filtering, above. For example, if we want to retrieve users in order of their last name (ascending), first name (ascending) and hire date (descending), the request might look like this www.example.com/users?sort='last_name\|first_name\|-hire_date'
*/
- (void) getAdvocatesAsyncWithAccountSlug:(NSString*) accountSlug
                page:(NSNumber*) page
                limit:(NSNumber*) limit
                filter:(NSString*) filter
                sort:(NSString*) sort
                completionBlock:(CompletedGetAdvocates) onCompleted;

/**
* Completion block definition for asynchronous call to Patch Advocate */
typedef void (^CompletedPatchAdvocate)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* Update partial elements of an advocate.
* @param    accountSlug    Required parameter: The account identifier
* @param    advocateToken    Required parameter: The advocate's token
* @param    advocatePatchForm    Required parameter: The body of the request
*/
- (void) patchAdvocateAsyncWithAccountSlug:(NSString*) accountSlug
                advocateToken:(NSString*) advocateToken
                advocatePatchForm:(NSArray<AdvocatePatchForm> *) advocatePatchForm
                completionBlock:(CompletedPatchAdvocate) onCompleted;

@end