//
//  AuthenticationsController.h
//  GeniusReferrals
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/17/2017
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"

@interface AuthenticationsController : BaseController

/**
* Completion block definition for asynchronous call to Authentications */
typedef void (^CompletedGetAuthentications)(BOOL success, HttpContext* context, id response, NSError* error);

/**
* Allow clients to test authentication on Genius Referrals platform.
*/
- (void) getAuthenticationsWithCompletionBlock:(CompletedGetAuthentications) onCompleted;

@end